# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  related_prs: false
  auto_review:
    enabled: true
    ignore_usernames:
      - "renovate[bot]"
    drafts: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
chat:
  auto_reply: true
